# Generated by Django 3.2.13 on 2023-12-02 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='duration',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
