# Generated by Django 3.2.13 on 2023-12-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_flight_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='duration',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
