# Generated by Django 4.2.7 on 2023-12-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0003_alter_flight_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='book_sum',
            new_name='economy_class_book_sum',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='capacity',
            new_name='economy_class_capacity',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='price',
            new_name='economy_class_price',
        ),
        migrations.AddField(
            model_name='flight',
            name='first_class_book_sum',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='first_class_capacity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='first_class_price',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=10),
            preserve_default=False,
        ),
    ]
