# Generated by Django 4.2.7 on 2023-12-14 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0005_order_class_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
